"""Shared plumbing for the QE GenAI toolkit: prompt-file output and JUnit XML
parsing.

JUnit XML is the deliberate interchange format -- Selenium suites (pytest,
TestNG, JUnit), Playwright (`--reporter=junit` / the `junit` reporter in
playwright.config), and Azure DevOps' PublishTestResults task all speak it,
so every tool here stays framework-agnostic.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional

PROMPT_FOOTER = (
    "\n---\n"
    "*Generated by qe-genai. Paste everything above this line into GitHub "
    "Copilot Chat (or any chat assistant). Review the answer before acting on "
    "it -- it is a draft, not a decision.*\n"
)


def write_prompt_file(out_dir: str | Path, name: str, prompt: str) -> Path:
    """Write a ready-to-paste prompt to `<out_dir>/<name>.prompt.md`."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{name}.prompt.md"
    path.write_text(prompt + PROMPT_FOOTER)
    return path


def read_text(path: str | Path, max_chars: int = 20000) -> str:
    """Read a text file, truncating the *middle* if huge -- for logs, the start
    (setup) and end (the actual failure) usually matter most."""
    text = Path(path).read_text(errors="replace")
    if len(text) <= max_chars:
        return text
    half = max_chars // 2
    return text[:half] + "\n\n[... truncated ...]\n\n" + text[-half:]


@dataclass
class TestResult:
    name: str
    classname: str
    status: str  # "passed" | "failed" | "error" | "skipped"
    time: float
    message: str = ""

    @property
    def full_name(self) -> str:
        return f"{self.classname}::{self.name}" if self.classname else self.name


def parse_junit(path: str | Path) -> list[TestResult]:
    """Parse a JUnit XML report (single <testsuite> or <testsuites> root)."""
    root = ET.parse(str(path)).getroot()
    suites = [root] if root.tag == "testsuite" else root.iter("testsuite")

    results: list[TestResult] = []
    for suite in suites:
        for case in suite.iter("testcase"):
            status, message = "passed", ""
            for tag, mapped in (("failure", "failed"), ("error", "error"), ("skipped", "skipped")):
                node = case.find(tag)
                if node is not None:
                    status = mapped
                    message = (node.get("message") or (node.text or "")).strip()
                    break
            results.append(
                TestResult(
                    name=case.get("name", ""),
                    classname=case.get("classname", ""),
                    status=status,
                    time=float(case.get("time") or 0.0),
                    message=message,
                )
            )
    return results


def parse_junit_many(paths: Iterable[str | Path]) -> dict[str, list[TestResult]]:
    """Parse several JUnit files (e.g. one per CI run), keyed by file stem in
    sorted order -- the basis for flakiness/trend analysis."""
    return {Path(p).stem: parse_junit(p) for p in sorted(map(str, paths))}


def summarize_results(results: list[TestResult]) -> dict[str, int]:
    counts = {"passed": 0, "failed": 0, "error": 0, "skipped": 0}
    for r in results:
        counts[r.status] = counts.get(r.status, 0) + 1
    counts["total"] = len(results)
    return counts


def format_failures(results: list[TestResult], limit: Optional[int] = None) -> str:
    failures = [r for r in results if r.status in ("failed", "error")]
    if limit is not None:
        failures = failures[:limit]
    if not failures:
        return "(no failures)"
    blocks = []
    for r in failures:
        blocks.append(f"### {r.full_name} [{r.status}, {r.time:.1f}s]\n```\n{r.message or '(no message)'}\n```")
    return "\n\n".join(blocks)
